@echo off
echo Starting the FixIt3D server...
start cmd /k "npm run dev"
echo Waiting for server to start...
timeout /t 5 /nobreak > nul
echo Opening the website in your browser...
start http://localhost:3000
